//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmeData.Mobile.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmeData.Mobile.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmarks.
        /// </summary>
        public static string Bookmarks {
            get {
                return ResourceManager.GetString("Bookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulgaria.
        /// </summary>
        public static string Bulgaria {
            get {
                return ResourceManager.GetString("Bulgaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case law.
        /// </summary>
        public static string CaseLaw {
            get {
                return ResourceManager.GetString("CaseLaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact with National DPAs.
        /// </summary>
        public static string ContactNationalDPA {
            get {
                return ResourceManager.GetString("ContactNationalDPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decisions.
        /// </summary>
        public static string Decisions {
            get {
                return ResourceManager.GetString("Decisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decision Support Tool.
        /// </summary>
        public static string DecisionSupportTool {
            get {
                return ResourceManager.GetString("DecisionSupportTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document content.
        /// </summary>
        public static string DocumentContent {
            get {
                return ResourceManager.GetString("DocumentContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erase.
        /// </summary>
        public static string Erase {
            get {
                return ResourceManager.GetString("Erase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EU legal framework.
        /// </summary>
        public static string EUlegalframework {
            get {
                return ResourceManager.GetString("EUlegalframework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to European Data Protection Board.
        /// </summary>
        public static string EuropeanDataProtectionBoard {
            get {
                return ResourceManager.GetString("EuropeanDataProtectionBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to European Data Protection Supervisor.
        /// </summary>
        public static string EuropeanDataProtectionSupervisor {
            get {
                return ResourceManager.GetString("EuropeanDataProtectionSupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to European Union.
        /// </summary>
        public static string EuropeanUnion {
            get {
                return ResourceManager.GetString("EuropeanUnion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequently asked questions.
        /// </summary>
        public static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GDPR Dictionary.
        /// </summary>
        public static string GdprDictionary {
            get {
                return ResourceManager.GetString("GdprDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GDPR Made Simple.
        /// </summary>
        public static string GDPRMadeSimple {
            get {
                return ResourceManager.GetString("GDPRMadeSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GDPR in Your Pocket.
        /// </summary>
        public static string GdprPocket {
            get {
                return ResourceManager.GetString("GdprPocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide for citizens.
        /// </summary>
        public static string GuideForCitizens {
            get {
                return ResourceManager.GetString("GuideForCitizens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide for SMEs.
        /// </summary>
        public static string GuideForSMEs {
            get {
                return ResourceManager.GetString("GuideForSMEs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guidelines.
        /// </summary>
        public static string Guidelines {
            get {
                return ResourceManager.GetString("Guidelines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International.
        /// </summary>
        public static string International {
            get {
                return ResourceManager.GetString("International", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International case law.
        /// </summary>
        public static string InternationalCaseLaw {
            get {
                return ResourceManager.GetString("InternationalCaseLaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International treaties.
        /// </summary>
        public static string InternationalTreaties {
            get {
                return ResourceManager.GetString("InternationalTreaties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italy.
        /// </summary>
        public static string Italy {
            get {
                return ResourceManager.GetString("Italy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal library.
        /// </summary>
        public static string LegalLibrary {
            get {
                return ResourceManager.GetString("LegalLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legislation.
        /// </summary>
        public static string Legislation {
            get {
                return ResourceManager.GetString("Legislation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main page.
        /// </summary>
        public static string MainPageCaption {
            get {
                return ResourceManager.GetString("MainPageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMEDATA Project is funded by the EU&apos;s Rights, Equality and Citizenship Programme (2014-2020).
        /// </summary>
        public static string MainPageFooter {
            get {
                return ResourceManager.GetString("MainPageFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National.
        /// </summary>
        public static string National {
            get {
                return ResourceManager.GetString("National", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National case law.
        /// </summary>
        public static string NationalCaseLaw {
            get {
                return ResourceManager.GetString("NationalCaseLaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National guidelines.
        /// </summary>
        public static string NationalGuidelines {
            get {
                return ResourceManager.GetString("NationalGuidelines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opinions.
        /// </summary>
        public static string Opinions {
            get {
                return ResourceManager.GetString("Opinions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other courts.
        /// </summary>
        public static string OtherCourts {
            get {
                return ResourceManager.GetString("OtherCourts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide practical guidance on GDPR rules to SME. Consist of the fallowing components....
        /// </summary>
        public static string PagesInfoText {
            get {
                return ResourceManager.GetString("PagesInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Prev {
            get {
                return ResourceManager.GetString("Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload bookmarks.
        /// </summary>
        public static string ReloadBookmarks {
            get {
                return ResourceManager.GetString("ReloadBookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved documents.
        /// </summary>
        public static string SavedDocuments {
            get {
                return ResourceManager.GetString("SavedDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save offline.
        /// </summary>
        public static string SaveOffline {
            get {
                return ResourceManager.GetString("SaveOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in documents.
        /// </summary>
        public static string SearchInDocuments {
            get {
                return ResourceManager.GetString("SearchInDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected entry.
        /// </summary>
        public static string SelectedEntry {
            get {
                return ResourceManager.GetString("SelectedEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SMEDATA Project aims at ensuring the highest degree of privacy and personal data protection through innovative tools for SMEs and citizens..
        /// </summary>
        public static string SmeDataIntroText {
            get {
                return ResourceManager.GetString("SmeDataIntroText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opinions.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supreme Administrative Court.
        /// </summary>
        public static string SupremeAdministrativeCourt {
            get {
                return ResourceManager.GetString("SupremeAdministrativeCourt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training materials.
        /// </summary>
        public static string TrainingMaterials {
            get {
                return ResourceManager.GetString("TrainingMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update all documents.
        /// </summary>
        public static string UpdateAllDocuments {
            get {
                return ResourceManager.GetString("UpdateAllDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Useful links.
        /// </summary>
        public static string UsefulLinks {
            get {
                return ResourceManager.GetString("UsefulLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
